urls.py
# from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.contrib.auth.views import password_reset

from django.contrib import admin
admin.autodiscover()

# using django-registration
from registration.views import activate
from registration.views import register

urlpatterns = patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login/login.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logout/logout.html'}),

    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset', \
            {'template_name': 'accounts/password/password_reset.html'}),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', \
            {'template_name': 'accounts/password/password_reset_done.html'}),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', \
            'django.contrib.auth.views.password_reset_confirm', \
            {'template_name': 'accounts/password/password_reset_confirm.html'}),
    url(r'^password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete', \
            {'template_name': 'accounts/password/password_reset_complete.html'}),

    # using django-registration
    url(r'^activate/complete/$', direct_to_template, {'template': 'activation_complete.html'}, name='registration_activation_complete'),
    url(r'^activate/(?P<activation_key>\w+)/$', activate, {'backend': 'registration.backends.default.DefaultBackend'}, name='registration_activate'),
    url(r'^register/$', register, {'backend': 'registration.backends.default.DefaultBackend'}, name='registration_register'),
    url(r'^register/complete/$', direct_to_template, {'template': 'registration_complete.html'}, name='registration_complete'),
    url(r'^register/closed/$', direct_to_template, {'template': 'registration_closed.html'}, name='registration_disallowed'),
    (r'', include('registration.auth_urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^about/$', direct_to_template, {'template': 'about.html'}),
    url(r'^contact/', include('django-goaltracking.contact.urls')),
    url(r'^getstarted/', include('django-goaltracking.goals.urls')),
    url(r'^goals/', include('django-goaltracking.goals.urls')),
    url(r'^profile/', include('django-goaltracking.profile.urls')),
    url(r'^$', include('django-goaltracking.goals.urls')),
)

contact/forms.py
from django import forms

class ContactForm(forms.Form):

    TOPIC_CHOICES = (
        ('', ''),
        ('HLP', 'Get Help'),
        ('BUG', 'Report A Bug'),
        ('OTR', 'Other'),
    )

    topic = forms.CharField(label='Topics', max_length=3, widget=forms.Select(choices=TOPIC_CHOICES))
    message = forms.CharField(label='Your Message', widget=forms.Textarea, error_messages={'required': 'Please enter a message.'})
    email = forms.CharField(label='Your Email Address', widget=forms.TextInput, error_messages={'required': 'Please enter an email address where you can be reached.'})

templates/accounts/password/password_reset.html
{% extends "base.html" %}

{% block page_title %}
    : Password Reset
{% endblock %}

{% block content %}

  <h2>Password reset</h2>

  <p>Forgotten your password? Enter your e-mail address below, and we'll e-mail instructions for setting a new one.</p>

    <div>
      <form method='post' action='./' class="form-inline">
        {% csrf_token %}
        <p>
          <label for="id_email">E-mail address:</label>
          <input id="id_email" type="text" name="email" maxlength="75" />
          <input type="submit" value="Reset my password" />
        </p>
      </form>
      {% if form.errors %}<p class="required">Your username and password didn't match. Please try again.</p>{% endif %}
    </div>

{% endblock %}

templates/accounts/password/password_reset_complete.html
{% extends "base.html" %}

{% block page_title %}
    : Password Reset
{% endblock %}

{% block content %}

  <h2>Password reset complete</h2>
  <p>Your password has been set.  You may go ahead and log in now.</p>
  <p><a href="/accounts/login/">Log in</a></p>

{% endblock %}

templates/accounts/password/password_reset_confirm.html
{% extends "base.html" %}

{% block page_title %}
    : Password Reset
{% endblock %}

{% block content %}

  <h2>Enter new password</h2>

  <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

  <form action="" method="post">
    {% csrf_token %}
    <p class="aligned wide"><label for="id_new_password1">New password:</label><input type="password" name="new_password1" id="id_new_password1" /></p>
    <p class="aligned wide"><label for="id_new_password2">Confirm password:</label><input type="password" name="new_password2" id="id_new_password2" /></p>
    <p><input type="submit" value="Change my password" /></p>
  </form>

{% endblock %}

templates/accounts/password/password_reset_done.html
{% extends "base.html" %}

{% block page_title %}
    : Password Reset
{% endblock %}

{% block content %}

  <h2>Password reset successful</h2>

  <p>We've e-mailed you instructions for setting your password to the e-mail address you submitted. You should be receiving it shortly.</p>

{% endblock %}