goals/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

from goals import views

urlpatterns = patterns('',
    url(r'^closedateset/(?P<id>\w+)/*$',        views.close_dateset,    name='close_dateset'),
    url(r'^addactivity/(?P<id>\w+)/*$',		views.add_activity, 	name='add_activity'),
    url(r'^goalset/',				views.goal_set,		name='create_goal_set'),
    url(r'^goalremove/(?P<id>\w+)/*$',          views.goal_remove,      name='remove_goal'),
    url(r'^goaladd/',				views.goal_add,         name='add_new_goal'),
    url(r'^summary/*$',             		views.show_summary,     name='goals_summary'),
    url(r'^complete/*$',                        views.show_complete,    name='goalset_complete'),
    url(r'^mobile/getstarted/*$',               views.show_mobile,      name='goals_mobile'),
    url(r'^mobile/*$',                          views.show_mobile,      name='goals_mobile'),
    url(r'^$',					views.show_home,        name='goals_home'),
)

goals/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User


class Goal(models.Model):
    user = models.ForeignKey(User, editable=False)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200, null=True, blank=True)
    complete = models.BooleanField(default=False, editable=False)

    def __unicode__(self):
        return u"%s" % (self.name)

    class Meta:
        ordering = ["name"]
        unique_together = ("user","name",) # user cannot have multiple goals with the same name

    """
    in-progress state: active == True AND complete == False
    complete cannot be True unless active already is
    """

class Goalset(models.Model):
    goal_one = models.ForeignKey(Goal, related_name='goal_one')
    goal_two = models.ForeignKey(Goal, related_name='goal_two')
    goal_three = models.ForeignKey(Goal, related_name='goal_three')
    goal_four = models.ForeignKey(Goal, related_name='goal_four')
    active_date = models.DateField('date started', auto_now_add=True, editable=False)
    complete_date = models.DateField('date completed', null=True, blank=True, editable=False)

    """
    set active_date and complete_date values 
    when the goalset is created
    """

    def __unicode__(self):
        return u"Goal Set %s" % (self.id)

    def goal_user(self):
        return u"%s" % (self.goal_one.user)

    def start_date(self):
        return u"%s" % (self.active_date.strftime('%h %d, %Y'))

    def end_date(self):
        return u"%s" % (self.complete_date.strftime('%h %d, %Y'))

    class Meta:
        ordering = ["active_date"]
        unique_together = ("goal_one","goal_two","goal_three","goal_four",)
        verbose_name_plural = "Goal Sets"

class Date(models.Model):
    goal = models.ForeignKey(Goal)
    week = models.IntegerField()
    day = models.IntegerField()
    activity_date = models.DateField(null=False, blank=False, editable=False)

    def __unicode__(self):
        return u"%s" % (self.goal.name)

    def goal_date(self):
        return u"%s" % (self.activity_date.strftime('%h %d, %Y'))

    def goal_user(self):
        return u"%s" % (self.goal.user)

    class Meta:
        ordering = ["goal"]
        unique_together = ("goal","week","day","activity_date",)


class Dateset(models.Model):
    date_one = models.ForeignKey(Date, related_name='date_one')
    date_two = models.ForeignKey(Date, related_name='date_two')
    date_three = models.ForeignKey(Date, related_name='date_three')
    date_four = models.ForeignKey(Date, related_name='date_four')
    complete = models.BooleanField(default=False, editable=True)

    def __unicode__(self):
        return u"%s" % (self.date_one.activity_date)

    def goal_user(self):
        return u"%s" % (self.date_one.goal.user)

    class Meta:
        unique_together = ("date_one","date_two","date_three","date_four")
        verbose_name_plural = "Date Sets"


class Activity(models.Model):
    date = models.ForeignKey(Date, editable=False)
    description = models.CharField(max_length=255)

    def __unicode__(self):
        return u"%s: %s" % (self.date, self.description)

    def activity_day(self):
        adate = self.date.activity_date.strftime('%h %d, %Y')
        return u"%s | %s | Week %s, Day %s | %s" % (self.date.goal.user.username, 
            self.date.goal.name, self.date.week, self.date.day, adate)

    class Meta:
        ordering = ["date"]
        verbose_name_plural = "Activities"


class Quote(models.Model):
    week = models.IntegerField()
    day = models.IntegerField()
    quote = models.CharField(max_length=255, unique=True)

    def __unicode__(self):
        return u"%s" % (self.quote)

    class Meta:
        ordering = ['week', 'day']
        unique_together = ('week','day',)


class Copy(models.Model):
    name = models.CharField(max_length=255, unique=True)
    content = models.TextField()

    def __unicode__(self):
        return u"%s" % (self.name)

    class Meta:
        ordering = ['name',]
        verbose_name_plural = "Static Copy"

goals/templates/complete.html
{% extends "base.html" %}

{% block page_title %}{% endblock %}

{% block content %}

  {% load copy_tags %}
  {% static_copy 'goal_complete' %}

  <div>

  <form action="" method="post" class="form-horizontal">
    <fieldset>
      {% csrf_token %}

      {% if goalset %}
        <div class="control-group">
          <label class="control-label" style="width: 200px;"><b>{{ goalset.goal_one }}</b> completed?</label>
          <div class="controls"><input type="checkbox" name="{{ goalset.goal_one.id }}" id="id_goal_one" /></div>
          <br clear="all">
          <label class="control-label" style="width: 200px;"><b>{{ goalset.goal_two }}</b> completed?</label>
          <div class="controls"><input type="checkbox" name="{{ goalset.goal_two.id }}" id="id_goal_two" /></div>
          <br clear="all">
          <label class="control-label" style="width: 200px;"><b>{{ goalset.goal_three }}</b> completed?</label>
          <div class="controls"><input type="checkbox" name="{{ goalset.goal_three.id }}" id="id_goal_three" /></div>
          <br clear="all">
          <label class="control-label" style="width: 200px;"><b>{{ goalset.goal_four }}</b> completed?</label>
          <div class="controls"><input type="checkbox" name="{{ goalset.goal_four.id }}" id="id_goal_four" /></div>
          <br clear="all">
        </div>
        <div class="control-group">
          <label class="control-label">
            <button type="submit" class="btn btn-primary" name="finish" value="finish">Finished!</button>
          </label>
        </div>

{% static_copy 'goal_complete_note' %}

      {% endif %}

    </fieldset>
  </form>

  </div>

{% endblock %}

goals/templates/goal_choose.html
{% load copy_tags %}

<form action="/goals/goalset/" method="post" class="well form-horizontal">
  <fieldset>
  {% csrf_token %}

  <div class="left half">
    <div class="control-group">
      <label class="control-label" for="multiSelect">Goal One:</label>
      <div class="controls">
        {{ setform.goal_one }}
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="multiSelect">Goal Two:</label>
      <div class="controls">
        {{ setform.goal_two }}
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="multiSelect">Goal Three:</label>
      <div class="controls">
        {{ setform.goal_three }}
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="multiSelect">Goal Four:</label>
      <div class="controls">
        {{ setform.goal_four }}
      </div>
    </div>
  </div>

  <div class="left half">
    {% static_copy 'goal_commit' %}
  </div>
  <div class="clear"></div>

  <div class="form-actions" style="margin: 0; padding-bottom: 0;">
    <button type="submit" class="btn btn-primary" name="commit" value="commit">COMMIT</button>
    <button class="btn" name="goback" value="goback">Or turn back now!</button>
  </div>

  {% if request.session.goal_set_errors %}
    {% for key, value in request.session.goal_set_errors.items %}
      <span class="required">{{ value }}</span>
    {% endfor %}
  {% endif %}

  </fieldset>
</form>

goals/templates/goal_date_set.html
<br clear="all">
<div class="date_outline">
  <table><tr valign="top">
  <td width="450">
    <h2>Week {{ date.date_one.week }}, Day {{ date.date_one.day }} - {{ date.date_one.activity_date|date:"F d, Y" }}</h2>
    <h3>{{ datesets_complete }} down, {{ datesets_remaining }} to go!</h3>
    <br clear="all">
  </td>
  <td width="150">&nbsp;</td>
  <td>
    {% load quote_tags %}
    <p><em>{% daily_quote date.date_one.week date.date_one.day %}</em></p>
  </td>
  </tr></table>

  <table><tr valign="top">
  <td colspan="4">
    {% if not date.complete %}
      {% if datesetform %}
        <form action="/goals/closedateset/{{date.id}}/" method="post" style="text-align: left;">
          {% csrf_token %}
          <input type='hidden' name='finished' value='True' />
          <button class="btn btn-primary">DATE COMPLETE</button>
        </form>
      {% endif %}
    {% else %}
      <h4>{{ date.date_one.activity_date|date:"F d, Y" }} is COMPLETE</h4>
    {% endif %}
  </td>
  </tr>
  <tr valign="top">
  <td>{% include "goal_one.html" %}</td>
  <td>{% include "goal_two.html" %}</td>
  <td>{% include "goal_three.html" %}</td>
  <td>{% include "goal_four.html" %}</td>
  </tr></table>

  <hr>

</div> <!-- end date_outline -->

goals/templates/goal_date_set_mobile.html
<br clear="all">
<div class="date_outline">
    <h3>Week {{ date.date_one.week }}, Day {{ date.date_one.day }} - {{ date.date_one.activity_date|date:"F d, Y" }} {% if date.complete %} is COMPLETE{% endif %}</h3>
    <h4>{{ datesets_complete }} down, {{ datesets_remaining }} to go!</h4>
    {% load quote_tags %}
    <p><em>{% daily_quote date.date_one.week date.date_one.day %}</em></p>

    {% include "goal_one_mobile.html" %}
    <hr>
    {% include "goal_two_mobile.html" %}
    <hr>
    {% include "goal_three_mobile.html" %}
    <hr>
    {% include "goal_four_mobile.html" %}
    {% if not date.complete %}
      {% if datesetform %}
        <form action="/goals/closedateset/{{date.id}}/" method="post" style="text-align: left;">
          {% csrf_token %}
          <input type='hidden' name='finished' value='True' />
          <button class="btn btn-primary" name="date-complete-mobile" value="date-complete-mobile">DATE COMPLETE</button>
        </form>
      {% endif %}
    {% endif %}

  <hr>

</div> <!-- end date_outline -->

goals/templates/goal_dateset_filler.html
{% if datesets %}
  {% for dateset in datesets %}
    <td class="stretch">
      {% if dateset.complete %}<div class="progfill">&nbsp;&nbsp;&nbsp;</div>{% endif %}
    </td>
  {% endfor %}
{% endif %}

goals/templates/goal_four.html
<div class="date_goal">
  <h3>Goal: <abbr title="{{ date.date_four.goal.description }}">{{ date.date_four.goal.name }}</abbr></h3>
</div>

<div class="date_goal_add">
{% if not date.complete %}
   {% if activityform %}
     <form action="/goals/addactivity/{{date.date_four.id}}/" method="post" style="border: 0px solid red; text-align: left;">
     {% csrf_token %}
     {{ activityform.description }}<br />
     <button type="submit" class="btn btn-primary" name"activity">ADD AN ACTIVITY</button>
     </form>
  {% endif %}
{% endif %}
</div>

<div class="date_goal_activities">
  {% load activity_tags %}
  <ul>
  {% for activity in date.date_four.id|date_activity %}
    <li>{{ activity }}</li>
  {% endfor %}
  </ul>
</div>

goals/templates/goal_four_mobile.html
<div class="date_goal">
  <h3>Goal: <abbr title="{{ date.date_four.goal.description }}">{{ date.date_four.goal.name }}</abbr></h3>
</div>

<div class="date_goal_add">
{% if not date.complete %}
   {% if activityform %}
     <form action="/goals/addactivity/{{date.date_four.id}}/" method="post">
       <fieldset>
         {% csrf_token %}
         {{ activityform.description }}<br />
         <button type="submit" class="btn btn-primary" name="activity-mobile" value="activity-mobile">ADD AN ACTIVITY</button>
       </fieldset>
     </form>
  {% endif %}
{% endif %}
</div>

<div class="date_goal_activities">
  {% load activity_tags %}
  <ul>
  {% for activity in date.date_four.id|date_activity %}
    <li>{{ activity }}</li>
  {% endfor %}
  </ul>
</div>

goals/templates/goal_one.html
<div class="date_goal">
  <h3>Goal: <abbr title="{{ date.date_one.goal.description }}">{{ date.date_one.goal.name }}</abbr></h3>
</div>

<div class="date_goal_add">
{% if not date.complete %}
   {% if activityform %}
     <form action="/goals/addactivity/{{date.date_one.id}}/" method="post">
     {% csrf_token %}
     {{ activityform.description }}<br />
     <button type="submit" class="btn btn-primary" name"activity">ADD AN ACTIVITY</button>
     </form>
  {% endif %}
{% endif %}
</div>

<div class="date_goal_activities">
  {% load activity_tags %}
  <ul>
  {% for activity in date.date_one.id|date_activity %}
    <li>{{ activity }}</li>
  {% endfor %}
  </ul>
</div>

goals/templates/goal_pool_mobile.html
{% if goalpool %}

  {% if getstarted %}
    <div style="padding-left: 15px;">
      <h3>Your list of ideas:</h3>
  {% endif %}

  <table cellpadding="5">
  {% for goal in goalpool %}
    <tr valign="top">
      <td>
      {% if not getstarted %}
        <form action="/goals/goalremove/{{ goal.id }}" method="post" class="form-horizontal" style="padding-bottom: 0;">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary" style="padding: 0px;" title="Remove" name="remove-mobile" value="remove-mobile">&#x2716;</button>
        </form>
      {% endif %}
      </td>
      <td><b>{{ goal.name }}</b></td>
      <td>{{ goal.description }}</td>
    </tr>
  {% endfor %}
  </table>

  {% if getstarted %}
    </div>
  {% endif %}

{% endif %}

goals/templates/goal_summary.html
{% extends "base.html" %}

{% block page_title %}
    : Summary
{% endblock %}

{% block header %}{% endblock %}

{% block content %}

  {% if act_one %}
    <p>
    {% for act in act_one %}
      {{ act.date.goal.name }}: {{ act.description }}<br>
    {% endfor %}
    </p>
  {% endif %}

  {% if act_two %}
    <p>
    {% for act in act_two %}
      {{ act.date.goal.name }}: {{ act.description }}<br>
    {% endfor %}
    </p>
  {% endif %}

  {% if act_three %}
    <p>
    {% for act in act_three %}
      {{ act.date.goal.name }}: {{ act.description }}<br>
    {% endfor %}
    </p>
  {% endif %}

  {% if act_four %}
    <p>
    {% for act in act_four %}
      {{ act.date.goal.name }}: {{ act.description }}<br>
    {% endfor %}
    </p>
  {% endif %}


{% endblock %}

goals/templates/goal_three.html
<div class="date_goal">
  <h3>Goal: <abbr title="{{ date.date_three.goal.description }}">{{ date.date_three.goal.name }}</abbr></h3>
</div>

<div class="date_goal_add">
{% if not date.complete %}
   {% if activityform %}
     <form action="/goals/addactivity/{{date.date_three.id}}/" method="post" style="border: 0px solid red; text-align: left;">
     {% csrf_token %}
     {{ activityform.description }}<br />
     <button type="submit" class="btn btn-primary" name"activity">ADD AN ACTIVITY</button>
     </form>
  {% endif %}
{% endif %}
</div>

<div class="date_goal_activities">
  {% load activity_tags %}
  <ul>
  {% for activity in date.date_three.id|date_activity %}
    <li>{{ activity }}</li>
  {% endfor %}
  </ul>
</div>

goals/templates/goal_two.html
<div class="date_goal">
  <h3>Goal: <abbr title="{{ date.date_two.goal.description }}">{{ date.date_two.goal.name }}</abbr></h3>
</div>

<div class="date_goal_add">
{% if not date.complete %}
   {% if activityform %}
     <form action="/goals/addactivity/{{date.date_two.id}}/" method="post" style="border: 0px solid red; text-align: left;">
     {% csrf_token %}
     {{ activityform.description }}<br />
     <button type="submit" class="btn btn-primary" name"activity">ADD AN ACTIVITY</button>
     </form>
  {% endif %}
{% endif %}
</div>

<div class="date_goal_activities">
  {% load activity_tags %}
  <ul>
  {% for activity in date.date_two.id|date_activity %}
    <li>{{ activity }}</li>
  {% endfor %}
  </ul>
</div>

goals/templates/mobile.html
{% extends "basemobile.html" %}

{% block content %}

  <div data-role="page" id="page-home">
    <div data-role="navbar">
      <ul>
        <li><a href="#page-home" class="ui-btn-active">Home</a></li>
        <li><a href="#page-summary">Summary</a></li>
        <li><a href="#page-contact">Contact</a></li>
        <!-- <li><a href="#page-profile">Profile</a></li> -->
        <!-- <li><a href="#page-logout">Log Out</a></li> -->
      </ul>
    </div><!-- /navbar -->
    <div data-role="content">
      {% if goalset %}
          {% if dates %}
            {% for date in dates %}
              {% include "goal_date_set_mobile.html" %}
            {% endfor %}
          {% endif %}
      {% else %}
          {% if ready %}
            {% if getstarted %}
              {% load copy_tags %}
              {% static_copy 'goal_choose' %}
              {% include "goal_choose_mobile.html" %}
              {% include "goal_pool_mobile.html" %}
            {% else %}
              {% load copy_tags %}
              {% static_copy 'goal_makelist' %}
              {% include "goal_add_form_mobile.html" %}
              {% include "goal_pool_mobile.html" %}
            {% endif %}
          {% else %}
            {% load copy_tags %}
            {% static_copy 'goal_makelist' %}
            {% include "goal_add_form_mobile.html" %}
            {% include "goal_pool_mobile.html" %}
        {% endif %}
      {% endif %}

    </div><!-- /content -->
  </div><!-- /page -->

  <div data-role="page" id="page-summary">
    <div data-role="navbar">
      <ul>
        <li><a href="#page-home">Home</a></li>
        <li><a href="#page-summary" class="ui-btn-active">Summary</a></li>
        <li><a href="#page-contact">Contact</a></li>
        <!-- <li><a href="#page-profile">Profile</a></li> -->
        <!-- <li><a href="#page-logout">Log Out</a></li> -->
      </ul>
    </div><!-- /navbar -->
    <div data-role="content">
      {% if goalset %}
        {{ percent_complete|floatformat:1 }} percent complete!
      {% endif %}
      <table cellpadding="5">
        <tr>
          <td>Date</td>
          <td nowrap="nowrap"><strong>{{ goalset.goal_one }}</strong></td>
          <td nowrap="nowrap"><strong>{{ goalset.goal_two }}</strong></td>
          <td nowrap="nowrap"><strong>{{ goalset.goal_three }}</strong></td>
          <td nowrap="nowrap"><strong>{{ goalset.goal_four }}</strong></td>
        </tr>
        {% if datesets %}
          {% for dateset in datesets %}
           <tr>
            <td>{{ dateset.date_one.week }}.{{ dateset.date_one.day }}</td>
            <td>{% if dateset.complete %} &#x2713; {% endif %}</td>
            <td>{% if dateset.complete %} &#x2713; {% endif %}</td>
            <td>{% if dateset.complete %} &#x2713; {% endif %}</td>
            <td>{% if dateset.complete %} &#x2713; {% endif %}</td>
          </tr>
          {% endfor %}
        {% endif %}
      </table>    
    </div><!-- /content -->
  </div><!-- /page -->

  <div data-role="page" id="page-contact">
    <div data-role="navbar">
      <ul>
        <li><a href="#page-home">Home</a></li>
        <li><a href="#page-summary">Summary</a></li>
        <li><a href="#page-contact" class="ui-btn-active">Contact</a></li>
        <!-- <li><a href="#page-profile">Profile</a></li> -->
        <!-- <li><a href="#page-logout">Log Out</a></li> -->
      </ul>
    </div><!-- /navbar -->
    <div data-role="content">
      <form action="/contact/" method="post">
        {% csrf_token %}
          <label>Topic:</label>
          <select name="topic" id="id_topic">
            <option value="" selected="selected"></option><option value="HLP">Get Help</option><option value="BUG">Report A Bug</option><option value="OTR">Other</option>
          </select>
          <br clear="all">
          <label>Message:</label><textarea id="id_message" rows="10" cols="40" name="message"></textarea>
          <label>Your Email Address:</label><input type="text" name="email" id="id_email" />
          <br clear="all">
          <button type="submit" name="send" value="send">Send</button>
      </form>
    </div><!-- /content -->
  </div><!-- /page -->

{% endblock %}

goals/templates/summary.html
{% extends "base.html" %}

{% block page_title %}
    : Summary
{% endblock %}

{% block content %}

  {% if goalset %}

    <div class="date_outline" style="margin-top: 10px;">
    <h2 style="color: gray;">{{ percent_complete|floatformat:1 }} percent complete!</h2>
    <br clear="all">

    <table>
      <tr valign="top">
        <td></td>
        {% if datesets %}
          {% load activity_tags %}
          {% for dateset in datesets %}
            <td>
	      {% if dateset.complete %}
                {% load activity_tags %}
                <a class="tip">&#x2713;
                  <span>

                    <p>{{ dateset.id|goal_activity_dates }}</p>

                    {% for activity in dateset.id|goal_activity %}
                      {{ activity.goal }}: {{ activity.activity }}<br>
                    {% endfor %}
                  </span>
                </a>
              {% else %}
                <div class="sum_date_label">{{ dateset.date_one.week }}.{{ dateset.date_one.day }}</div>
	      {% endif %}
            </td>
          {% endfor %}
        {% endif %}
      </tr>
      <tr>
        <td><div class="sum_label sum_goal_label">{{ goalset.goal_one }}</div></td>
        {% include 'goal_dateset_filler.html' %}
      </tr>
      <tr>
        <td><div class="sum_label sum_goal_label">{{ goalset.goal_two }}</div></td>
        {% include 'goal_dateset_filler.html' %}
      </tr>
      <tr>
        <td><div class="sum_label sum_goal_label">{{ goalset.goal_three }}</div></td>
        {% include 'goal_dateset_filler.html' %}
      </tr>
      <tr>
        <td><div class="sum_label sum_goal_label">{{ goalset.goal_four }}</div></td>
        {% include 'goal_dateset_filler.html' %}
      </tr>
    </table>

  {% endif %}

{% endblock %}